-- 1. Tabla USUARIOS
CREATE TABLE USUARIOS (
    ID_USUARIO INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    FOTO_PERFIL VARCHAR(255) DEFAULT 'default_user.png',
    DESCRIPCION VARCHAR(500),
    ROL VARCHAR(20) DEFAULT 'usuario',
    CONSTRAINT USUARIOS_PK PRIMARY KEY (ID_USUARIO)
);

-- 2. Tabla RECETAS
CREATE TABLE RECETAS (
    ID_RECETA INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_USUARIO INT NOT NULL,
    TITULO VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(500),
    IMAGEN_RUTA VARCHAR(255),
    FECHA_PUBLICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT RECETAS_PK PRIMARY KEY (ID_RECETA),
    CONSTRAINT RECETAS_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

-- 3. Tabla LIKES
CREATE TABLE LIKES (
    ID_USUARIO INT NOT NULL,
    ID_RECETA INT NOT NULL,
    CONSTRAINT LIKES_PK PRIMARY KEY (ID_USUARIO, ID_RECETA),
    CONSTRAINT LIKES_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT LIKES_RECETA_FK FOREIGN KEY (ID_RECETA) REFERENCES RECETAS(ID_RECETA)
);

-- 4. Tabla COMENTARIOS
CREATE TABLE COMENTARIOS (
    ID_COMENTARIO INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_USUARIO INT NOT NULL,
    ID_RECETA INT NOT NULL,
    TEXTO VARCHAR(500) NOT NULL,
    FECHA_COMENTARIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT COMENTARIOS_PK PRIMARY KEY (ID_COMENTARIO),
    CONSTRAINT COMENTARIOS_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT COMENTARIOS_RECETA_FK FOREIGN KEY (ID_RECETA) REFERENCES RECETAS(ID_RECETA)
);

-- 5. Tabla SEGUIDORES
CREATE TABLE SEGUIDORES (
    ID_SEGUIDOR INT NOT NULL,
    ID_SEGUIDO INT NOT NULL,
    FECHA_SEGUIMIENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT SEGUIDORES_PK PRIMARY KEY (ID_SEGUIDOR, ID_SEGUIDO),
    CONSTRAINT SEGUIDORES_SEGUIDOR_FK FOREIGN KEY (ID_SEGUIDOR) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT SEGUIDORES_SEGUIDO_FK FOREIGN KEY (ID_SEGUIDO) REFERENCES USUARIOS(ID_USUARIO)
);

-- 6. Tabla MENSAJES
CREATE TABLE MENSAJES (
    ID_MENSAJE INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    ID_EMISOR INT NOT NULL,
    ID_RECEPTOR INT NOT NULL,
    TEXTO VARCHAR(1000) NOT NULL,
    FECHA_ENVIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT MENSAJES_PK PRIMARY KEY (ID_MENSAJE),
    CONSTRAINT MENSAJES_EMISOR_FK FOREIGN KEY (ID_EMISOR) REFERENCES USUARIOS(ID_USUARIO),
    CONSTRAINT MENSAJES_RECEPTOR_FK FOREIGN KEY (ID_RECEPTOR) REFERENCES USUARIOS(ID_USUARIO)
);